Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-09, with the labels that each got.

#351 ⚙️ 운영서버 prod 프로필 활성화
  .github/workflows/deploy.yml
  docker/Dockerfile
Labels: ⚙️ chore

#353 ✨ 백엔드 최종 요구사항 반영
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: ✨ feature, 🏅 P1

#355 :zap: 수락 거절 수 지원가능 여부 응답값 리턴
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature, 🚀 refactor

#358 Feature/#357 수락 거절 응답값 변경
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: 🚀 refactor, 🥈 P2

#361 ♻️ 교내 및 교외 스터디 게시글 작성 API를 각각 게시글 이미지 업로드 API와 통합
  src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyCreateResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: ✨ feature, 🏅 P1

#363 ✨ 비로그인 유저도 게시글 전체 목록 조회 및 상세 조회 가능하도록 추가
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyNoLoginController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoNoLoginResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostNoLoginResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyNoLoginService.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
Labels: ✨ feature
