Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-03, with the labels that each got.

#93 ✨ 혼밥 매칭 시 정해진 대기 시간이 지났을 경우 매칭 TIME_OUT
  src/main/java/com/sejong/sejongpeer/domain/honbab/dto/request/RegisterHonbabRequest.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
Labels: ✨ feature

#96 :bug: Request 어노테이션 수정
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
Labels: 🍡 bug/error, 🏅 P1

#99 RefreshToken 검증 임시 중지
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/global/common/constants/SwaggerUrlConstants.java
  src/main/java/com/sejong/sejongpeer/global/common/constants/UrlConstants.java
  src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java
  src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
  src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
Labels: 🍡 bug/error

#92 :gear: prod yml 생성
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#107 🐛 유저의 버디 엔티티를 찾을 때 찾는 상태를 FOUNDED_BUDDY로 변경
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
Labels: 🍡 bug/error, 🏅 P1

#105 :bug: HonbabMatched, BuddyMatched BaseAuditEntity 상속
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
Labels: 🍡 bug/error, 🏅 P1

#102 🐛 request DTO validation 수정
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/test/java/com/sejong/sejongpeer/domain/member/api/MemberControllerTest.java
Labels: 🍡 bug/error, 🏅 P1

#104 ♻️ Access Toekn 재발급 방식 변경
  src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/TokenReissueRequest.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/TokenReissueResponse.java
  src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
  src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
Labels: 🚀 refactor, 🥈 P2

#109 :bug: '후배' 조건에서 학번 비교 잘못된 부분 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/ClassTypeOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
Labels: 🍡 bug/error, 🏅 P1

#112 Revert "♻️ Access Toekn 재발급 방식 변경"
  src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/TokenReissueRequest.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/TokenReissueResponse.java
  src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
  src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
Labels: 🍡 bug/error

#114 ✨혼밥 신청 후 중도 취소 기능
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature

#116 ✨ 버디 신청인원수, 혼밥 신청인원수 리턴 기능
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/ActiveCustomersCountResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
Labels: ✨ feature

#111 🐛 refresh token이 유효할 시, access token 재설정하는 로직 복구
  src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
Labels: 🍡 bug/error, 🏅 P1

#118 :bug: 회원탈퇴 버그 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
Labels: 🍡 bug/error, 🏅 P1

#120 ✨ 혼밥 밥짝꿍 매칭 이후 15분 동안 혼밥 신청 금지
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature

#122 🐛 버디 짝매칭 이후 수락/거절 로직 문제 개선 및 해결
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
Labels: 🍡 bug/error, 🏅 P1

#124 ✨ 혼밥 매칭 후 재신청 가능한 상태 추가 및 상태 체크 시 업데이트
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/HonbabStatus.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
Labels: ✨ feature, 🏅 P1

#127 ✨ Sejong auth webClient 추가
  src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/SejongAuthRequest.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SejongAuthClientResponse.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SejongAuthResponse.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/global/config/WebClientConfig.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
Labels: ✨ feature, 🏅 P1

#131 ✨ 버디 매칭 거절 시 거절한 유저에게 패널티 문자 전송 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature, 🏅 P1

#133 :art: 24시간 패널티 -> 1시간 패널티
  src/main/java/com/sejong/sejongpeer/domain/buddy/constant/LimitTimeConstant.java
Labels: 🚀 refactor, 🏅 P1

#128 ♻️ 혼밥 service 구조 리펙토링
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
Labels: 🚀 refactor

#141 🐛 ErrorCode 수정
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🍡 bug/error

#139 ✨ 버디 등록 3회 제한 기능
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature

#142 ✨ 버디 양쪽 모두 매칭 수락 이후 모든 상대 정보 반환 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: ✨ feature, 🏅 P1

#145 ⚙️ develop 스테이징 서버 배포
  .github/workflows/staging_deploy.yml
  appspec-staging.yml
  scripts/staging_deploy.sh
Labels: ⚙️ chore

#147 ♻️ 버디 짝매칭 이후 수락/거절 로직 쿼리 최적화 리팩토링
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
Labels: 🚀 refactor

#152 :green_heart: develop브랜치에 push시에만 action실행
  .github/workflows/staging_deploy.yml
Labels: ⚙️ chore

#150 🐛 REJECT상태인 버디 등록 시 상태값 반환에서 처리
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/BuddyStatus.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: 🍡 bug/error, 🏅 P1

#154 :green_heart: develop 2번 빌드되는거 수정
  .github/workflows/build.yml
Labels: ⚙️ chore

#156 main 브랜치 develop 병합
  .github/workflows/build.yml
  .github/workflows/staging_deploy.yml
  appspec-staging.yml
  scripts/staging_deploy.sh
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/constant/LimitTimeConstant.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/BuddyStatus.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: ⚙️ chore

#158 ♻️ 버디 상태값 요청에 MATCHING_COMPLETED 된 count 같이 넘겨주도록 변경
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: ✨ feature, 🚀 refactor

#161 ♻️ 버디 수락/거절 및 자동 거절 처리 스케쥴러 BuddyMatched 찾는 방식 변경
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
Labels: 🚀 refactor

#163 ♻️ Buddy에서 BuddyMatched 찾는 방식 쿼리문 줄이도록 리팩토링
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: 🚀 refactor

#171 ♻️ 서비스 코드 개선
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/ActiveCustomersCountResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/CompletedPartnerInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/dto/response/HonbabMatchingStatusResponse.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/ExistsCheckResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🚀 refactor, 🥈 P2

#169 ♻️ 버디 수락/거절 엔드 포인트, 메소드 명 변경 및 모든 상대 정보 반환 stream 리펙토링
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyMatchingController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: 🚀 refactor
