Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-01, with the labels that each got.

#5 chore: 프로젝트 구성 ISSUE 템플릿 추가
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/⚙️-chore.md
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/📝-documentation.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/develop_pull_request.yml
  build.gradle
  src/main/java/com/sejong/sejongpeer/SejongpeerApplication.java
  src/test/java/com/sejong/sejongpeer/SejongpeerApplicationTests.java
Labels: 🏅 P1, ⚙️ chore

#8 :safety_vest: chore: 전역 처리를 위한 RestControllerAdvice 추가
  build.gradle
  src/main/java/com/sejong/sejongpeer/global/common/constants/EnvironmentConstants.java
  src/main/java/com/sejong/sejongpeer/global/common/request/.gitkeep
  src/main/java/com/sejong/sejongpeer/global/common/response/GlobalResponse.java
  src/main/java/com/sejong/sejongpeer/global/common/response/GlobalResponseAdvice.java
  src/main/java/com/sejong/sejongpeer/global/error/ErrorResponse.java
  src/main/java/com/sejong/sejongpeer/global/error/GlobalExceptionHandler.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/CustomException.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/global/util/SpringEnvironmentUtil.java
Labels: 🏅 P1, ⚙️ chore

#10 :feat: User 도메인 추가 및 회원가입/로그인 기능 구현
  .editorconfig
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/SignInRequest.java
  src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
  src/main/java/com/sejong/sejongpeer/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/JwtService.java
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/SignUpRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/type/Gender.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/type/Status.java
  src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/global/config/JpaAuditingConfig.java
  src/main/java/com/sejong/sejongpeer/global/util/CookieUtil.java
  src/main/java/com/sejong/sejongpeer/security/MemberDetails.java
  src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
  src/main/java/com/sejong/sejongpeer/security/constant/HeaderConstants.java
  src/main/java/com/sejong/sejongpeer/security/util/JwtProvider.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/sejong/sejongpeer/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/sejong/sejongpeer/util/DomainObjectUtil.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 🏅 P1

#14 :sparkles: feat: BaseEntity 추가
  src/main/java/com/sejong/sejongpeer/domain/common/BaseAuditEntity.java
  src/main/java/com/sejong/sejongpeer/domain/common/BaseEntity.java
Labels: ✨ feature, 🏅 P1

#15 :memo: chore: SwaggerConfig 추가
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🏅 P1, ⚙️ chore

#21 :sparkles: CollegeMajor 앤티티 생성 & 조회 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeMajorController.java
  src/main/java/com/sejong/sejongpeer/domain/college/dto/CollegeMajorResponse.java
  src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeMajor.java
  src/main/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepository.java
  src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
  src/test/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepositoryTest.java
Labels: ✨ feature, 🥈 P2

#17 :sparkles: Study Entity 도메인 추가
  src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeMajorController.java
  src/main/java/com/sejong/sejongpeer/domain/college/dto/CollegeMajorResponse.java
  src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeMajor.java
  src/main/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepository.java
  src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/dto/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/RecruitmentStatus.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyType.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/service/.gitkeep
  src/test/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepositoryTest.java
Labels: ✨ feature, 🏅 P1
