Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-04, with the labels that each got.

#175 :recycle: SecurityContextHolder에서 MemberId 추출 부분 메소드로 분리
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/security/util/SecurityContextUtil.java
Labels: 🚀 refactor, 🥉 P3

#167 ♻️ 엔드포인트, Optional 리펙토링
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/request/BuddyRegistrationRequest.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
Labels: 🚀 refactor

#37 ✨ 스터디 신청 현황 엔티티 구성
  src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/entity/ExternalActivity.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/entity/ExternalActivityStudy.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/LectureStudy.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/RecruitmentStatus.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyType.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/StudyRelationCreateResponse.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/type/StudyMatchingStatus.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepositoryCustom.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
Labels: ✨ feature, 🏅 P1

#187 ⚙️ Spring Actuator 구성
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/staging_deploy.yml
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: 🥈 P2, ⚙️ chore
