Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-05, with the labels that each got.

#180 ✨ 단과대 별 개설된 수업 정보 조회
  src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/controller/LectureController.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/dto/CollegeLessonProfessorResponse.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/repository/LectureRepository.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/service/LectureService.java
Labels: ✨ feature, 🏅 P1

#184 ✨ MemberUtil 구현
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeMajor.java
  src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/entity/ExternalActivity.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
  src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/global/util/MemberUtil.java
  src/main/java/com/sejong/sejongpeer/global/util/SecurityUtil.java
  src/main/java/com/sejong/sejongpeer/security/MemberDetails.java
  src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java
  src/test/java/com/sejong/sejongpeer/util/MemberUtilTest.java
Labels: 🚀 refactor, 🥈 P2

#197 :bug: `@Tag` 넘버링 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/controller/LectureController.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
Labels: 🍡 bug/error

#198 ✨ 스터디 스크랩 기능
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dto/request/StudyScrapCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapResponse.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/entity/Scrap.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/entity/ScrapType.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#190 ✨스터디 게시글 무한 스크롤 전체 조회, 단건 상세 조회, 게시글 다중 조건 검색 API
  src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/repository/ExternalActivityStudyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
  src/main/java/com/sejong/sejongpeer/domain/lecturestudy/repository/LectureStudyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#202 ✨축제 기간 혼밥 탈출 기능 변경
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
Labels: ✨ feature, 🏅 P1
