Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-07, with the labels that each got.

#206 ✨ 스터디 지원 및 게시글 별 지원자 수 현황 추가
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/request/StudyApplyRequest.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/StudyRelationCreateResponse.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#212 스터디 조기마감 병합
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature

#216 ✨ 교외 활동 카테고리 유형 정보 조회
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/controller/ExternalActivityController.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/dto/ExternalActivityCategoryResponse.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/service/ExternalActivityService.java
Labels: ✨ feature, 🏅 P1

#219 🐛 Swagger 상에서 access token, refresh token 넣고 request, response 확인 가능하도록 수정
  src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeMajorController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java
Labels: 🍡 bug/error, 🏅 P1

#220 게시글 생성 API, Study 엔티티 밑 request 수정
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/entity/ExternalActivity.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/Frequency.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyMethod.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
Labels: ✨ feature, 🥈 P2

#221 게시글 생성 및 Study 엔티티 수정 병합
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/entity/ExternalActivity.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/Frequency.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyMethod.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
Labels: ✨ feature

#222 :sparkles: 태그 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/StudyTagMap.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Tag.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyTagMapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/TagRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/TagService.java
  src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
Labels: ✨ feature, 🏅 P1

#223 스터디 생성 시 태그 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/StudyTagMap.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Tag.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyTagMapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/TagRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/TagService.java
  src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
Labels: ✨ feature, 🏅 P1

#232 ✨ 교내외 스터디 게시글 단건 삭제
  src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#233 ✨ 스터디 게시글 이미지 base64 string 처리 및 병렬 S3 업로드, 상세 조회 시 이미지 반환 로직 수정
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
  src/main/java/com/sejong/sejongpeer/domain/image/dto/request/StudyImageUploadRequest.java
  src/main/java/com/sejong/sejongpeer/domain/image/dto/response/StudyImageUrlResponse.java
  src/main/java/com/sejong/sejongpeer/domain/image/entity/Image.java
  src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/infra/config/aws/S3Config.java
Labels: ✨ feature, 🥈 P2

#236 ✨ 스터디 지원자에 대한 수락/거절 상태 변경 및 수락일 경우 참여 인원 증가 처리 API
  src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/request/StudyMatchingRequest.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#243 Feature/#238
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/TagService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/AppliedStudyResponse.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature

#247 ✨ 게시글 상세 조회 스터디 모집 인원 및 가입된 인원 수
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
Labels: ✨ feature, 🏅 P1

#248 ✨ 게시글 별 스크랩 수 조회
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapCountResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
Labels: ✨ feature, 🏅 P1

#252 ✨ 스터디 지원 취소 및 패널티 부여
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/type/StudyMatchingStatus.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#254 :sparkles: 스터디 수정 시 게시자만 수정가능
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: ✨ feature

#258 🐛 스터디 지원 취소 및 재지원 로직 수정
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🍡 bug/error, 🏅 P1

#262 🐛 스터디 지원 404 bad request
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: 🍡 bug/error, 🏅 P1

#264 ♻️ 게시글 무한스크롤 전체 조회, 게시글 상세 조회, 게시글 검색 response에 게시글 별 스크랩 수 함께 반환
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: 🚀 refactor, 🥉 P3

#265 ✨ 지원자 있을 경우, 스터디 삭제되었을 경우, 지원 거절당했을 경우 문자 발송
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature, 🥈 P2

#267 ✨StudyPostInfoResponse, StudyTotalPostResonse DTO data 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
Labels: ✨ feature, 🏅 P1

#269 ✨ 게시글 이미지 수정
  src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
  src/main/java/com/sejong/sejongpeer/domain/image/repository/ImageRepository.java
  src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
Labels: ✨ feature, 🏅 P1

#272 🐛 StudyTatalPostResopnse hasImage 게시글 이미지 포함 여부 로직 수정
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
Labels: 🏅 P1

#274 ✨ 마이페이지 내가 좋아요한 글 목록 전체 조회
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: ✨ feature, 🏅 P1

#276 ✨ 게시글 목록 조회 공용 response 필드 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
Labels: ✨ feature

#277 ⚡ 백에서 S3 업로드 로직 개선
  src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
  src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🚀 refactor

#280 ♻️ 세종스터디 코드 리펙토링
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: 🚀 refactor
