Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-02, with the labels that each got.

#25 ✨ feat: Querydsl 활성화
  build.gradle
  src/main/java/com/sejong/sejongpeer/global/config/QuerydslConfig.java
Labels: ✨ feature, 🏅 P1

#26 ✨ feat: 스터디 CRUD 1차 구현
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/study/api/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyUpdateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyCreateResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyFindResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyUpdateResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepositoryCustom.java
  src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepositoryImpl.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/.gitkeep
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/test/java/com/sejong/sejongpeer/TestQuerydslConfig.java
  src/test/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepositoryTest.java
  src/test/java/com/sejong/sejongpeer/domain/member/repository/MemberRepositoryTest.java
Labels: ✨ feature, 🏅 P1

#35 :gear: docker yml 포트포워딩 임시 변경
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
Labels: ⚙️ chore

#43 🐛 회원정보 수정 기능 fix
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/request/AccountFindRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/AccountFindResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/ExistsCheckResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/NicknameCheckResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/type/MemberInfo.java
  src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
  src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yml
  src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java
Labels: 🍡 bug/error, ✨ feature, 🚀 refactor, 🏅 P1

#50 :bug: MySQL 예약어 중복에러 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
Labels: 🍡 bug/error, 🏅 P1

#51 :bug: spotless 제거 및 checkstyle 적용
  .github/workflows/build.yml
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
Labels: 🍡 bug/error, 🥈 P2

#54 ♻️ Buddy Range, Type 엔티티 네이밍 변경 및 Buddy entity구조 변경
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/ClassTypeOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/CollegeMajorOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/GenderOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/GradeOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/Status.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/type/Status.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/type/BuddyRange.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/type/BuddyType.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
Labels: ✨ feature, 🏅 P1

#39 ✨ 버디 매칭 기능 및 스케줄러 구현
  build.gradle
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/ClassTypeOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/CollegeMajorOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/GenderOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/GradeOption.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/type/Status.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/util/BuddyFilter.java
  src/main/java/com/sejong/sejongpeer/global/config/SchedulerConfig.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
  src/main/resources/application-infra.yml
  src/main/resources/application.yml
  src/test/java/com/sejong/sejongpeer/SejongpeerApplicationTests.java
Labels: ✨ feature, 🏅 P1

#48 ✨ 버디 등록 기능
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/request/RegisterRequest.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: ✨ feature

#57 ♻️ 버디 추가 시 이전 패널티 확인
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🍡 bug/error, ✨ feature

#55 ✨ 버디 신청 중도 취소 (매칭 전)
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: ✨ feature

#60 ♻️ 버디 중도취소 input값 삭제 및 등록된 버디가 없을 때 취소 예외처리
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: 🍡 bug/error

#66 :sparkles: 버디 등록 시, 짝 찾기 실행
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
Labels: ✨ feature

#64 :bug: 회원정보 계정 찾기 기능 변경
  src/main/java/com/sejong/sejongpeer/domain/member/dto/request/AccountFindRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/request/PasswordResetRequest.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/AccountFindResponse.java
  src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/domain/member/type/AccountFindOption.java
  src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java
Labels: 🍡 bug/error, 🏅 P1

#59 ✨ 버디 매칭 상대 업데이트 및 매칭 거절 유저에 대한 패널티 부여
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyMatchingController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/request/MatchingResultRequest.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🏅 P1

#71 🐛 상태에 따른 버디 조회 메소드 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
Labels: 🍡 bug/error, 🏅 P1

#76 ✨ 버디 짝매칭 성공 시 문자 발송 기능 추가
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature

#75 🐛 Buddy 등록 시 매칭에서 BuddyMatched가 DB에 저장되지 않던 오류 수정
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: 🍡 bug/error

#78 🐛 짝매칭 성사가 되었을 때 BuddyMatched 엔티티에서 target Buddy만을 받아오는 문제 해결
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
Labels: 🍡 bug/error

#72 ✨ 혼밥 엔티티 구성 및 매칭 기능 구현
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/GenderOption.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/HonbabStatus.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/MenuCategoryOption.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/type/HonbabMatchedStatus.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/scheduler/HonbabMatchingScheduler.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/util/HonbabFilter.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
  src/main/resources/application-dev.yml
Labels: ✨ feature, 🏅 P1

#83 🐛 HonBab, HonbabMatched엔티티에서 id값 자동설정
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
Labels: 🍡 bug/error, 🏅 P1

#79 ✨ Buddy, BuddyMatched가 Complete일 때 응답 메소드 구현
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/CompletedPartnerInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingPartnerInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature

#87 ✨ 혼밥 짝꿍 매칭 성공 시 상대방 정보 제공
  src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/dto/response/MatchingPartnerInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabMatchedRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: ✨ feature

#89 :recycle: 등록된 버디가 없을 때 상대정보 요청시 null 리턴
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
  src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
Labels: 🚀 refactor

#86 :sparkles: 로그인 response 수정
  src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SignInResponse.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/domain/member/dto/response/MemberInfoResponse.java
Labels: ✨ feature, 🏅 P1
