Repository SejongPeer/SejongPeer-back, pull requests merged in 2024-08, with the labels that each got.

#282 🐛 스터디 지원 거절 처리 문자 발송 Enum IllegalArgumentException 해결
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsService.java
Labels: 🍡 bug/error, 🏅 P1

#284 ♻️ 스터디 조기 마감 엔드포인트 수정
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
Labels: 🚀 refactor

#286 ✨ 스터디 조기마감 시 스터디 게시글 모집 상태 변경
  src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature

#288 ✨ 스터디 게시글 별 모집 상태 및 지원자 매칭 상태 반환 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature

#293 ✨ 스터디 지원자 조회 모집 인원, 수락 인원 응답 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
Labels: ✨ feature

#295 :sparkles: 스터디 조기마감 시 이미 마감된 스터디 예외처리
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🚀 refactor, 🥉 P3

#297 ♻️ 세종버디 facade class가 총괄 하도록 구현 및 여러 서비스 코드 의존성 제거
  src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyManagementFacade.java
  src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
Labels: 🚀 refactor

#303 :sparkles: 스터디 지원자 리스트 중 PENDING, ACCEPT, REJECT 지원자만 리턴
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature

#308 ♻️ 회원 Service Layer 분리
  src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
  src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
  src/main/java/com/sejong/sejongpeer/domain/member/service/MemberVerificationService.java
Labels: 🚀 refactor

#315 ✨AWS ElastiCache Redis 구축
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/sejong/sejongpeer/SejongpeerApplication.java
  src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
  src/main/java/com/sejong/sejongpeer/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
  src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/service/ExternalActivityService.java
  src/main/java/com/sejong/sejongpeer/global/config/CacheConfig.java
  src/main/java/com/sejong/sejongpeer/global/config/RedisConfig.java
  src/main/java/com/sejong/sejongpeer/infra/config/properties/PropertiesConfig.java
  src/main/java/com/sejong/sejongpeer/infra/config/properties/RedisProperties.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: 🚀 refactor, ⚙️ chore

#317 ♻️ 세종스터디 문자 메세지 최종
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
Labels: 🚀 refactor

#319 ♻️ 게시글 검색 Nullable 필터링 가능하도록 수정
  .github/workflows/deploy.yml
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/config/CacheConfig.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🚀 refactor, 🏅 P1

#322 🐛 게시글 필터링 조건 쿼리스트링으로 받도록 통일
  src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: 🍡 bug/error

#324 🐛 게시글 검색어 Null 처리 추가
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
Labels: 🍡 bug/error

#327 ♻️ 캐시 기능 개선
  build.gradle
  src/main/java/com/sejong/sejongpeer/SejongpeerApplication.java
  src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
  src/main/java/com/sejong/sejongpeer/domain/externalactivity/service/ExternalActivityService.java
  src/main/java/com/sejong/sejongpeer/global/config/CacheConfig.java
  src/main/java/com/sejong/sejongpeer/global/config/RedisConfig.java
  src/main/java/com/sejong/sejongpeer/infra/config/properties/RedisProperties.java
  src/main/resources/ehcache.xml
Labels: 🚀 refactor

#329 :bug: 제목이 10자 미만일 경우 Exception Error 수정
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: 🍡 bug/error, 🏅 P1

#332 🐛 스터디 지원자 수락 시 모집 인원까지만 받도록 예외 처리 추가
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🍡 bug/error, ✨ feature

#337 ✨ 로그인한 유저의 스터디 게시글 별 지원 여부 반환 추가
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
Labels: ✨ feature

#338 ♻️ 세종스터디 마이페이지 내가 작성한, 내가 지원한 목록에 대해 역순 정렬
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: 🚀 refactor

#339 🐛 도커컴포즈 블루그린 무중단 배포 최종 완료
  .github/workflows/deploy.yml
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  scripts/deploy.sh
Labels: 🍡 bug/error, ⚙️ chore

#341 ✨ 게시글 상세 조회 유저의 해당 게시글 스크랩 여부 추가
  src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
Labels: ✨ feature

#343 ♻️ 스터디 스크랩 추가 시 scrapId 명시적으로 반환
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapCreateResponse.java
Labels: 🚀 refactor

#345 ✨ 스터디 모집 인원 다 찼을 경우 모집 마감 문자 발송
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: ✨ feature

#347 🐛 스터디 게시글 제목 substring exception 처리
  src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
  src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
Labels: 🍡 bug/error

#349 ♻️ 스크랩 삭제 시 scrapId 사용 안하는 로직으로 대체
  src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
  src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
Labels: 🚀 refactor
